//
// Created by Miguel Bazan on 10/06/26.
//

#ifndef FUNCIONESARBOLES_ELEMENTOARBOLBINARIO_H
#define FUNCIONESARBOLES_ELEMENTOARBOLBINARIO_H

struct ElementoArbolBinario{
    int numero;
};

#endif //FUNCIONESARBOLES_ELEMENTOARBOLBINARIO_H
