//
// Created by Miguel Bazan on 23/06/26.
//

#ifndef FUNCIONESABB_ELEMENTOARBOLBINARIOBUSQUEDA_H
#define FUNCIONESABB_ELEMENTOARBOLBINARIOBUSQUEDA_H

struct ElementoArbolBinarioBusqueda {
    int numero;
};

#endif //FUNCIONESABB_ELEMENTOARBOLBINARIOBUSQUEDA_H
